package com.github.fukkitmc.fukkit.access.net.minecraft.server.network;

import com.github.fukkitmc.fukkit.access.net.minecraft.entity.player.PlayerEntityAccess;
import com.mojang.datafixers.util.Either;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.text.Text;
import net.minecraft.util.Unit;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.dimension.DimensionType;
import org.bukkit.Location;
import org.bukkit.WeatherType;
import org.bukkit.craftbukkit.entity.CraftPlayer;
import org.bukkit.event.player.PlayerTeleportEvent;

public interface ServerPlayerEntityAccess extends PlayerEntityAccess<CraftPlayer> {
	String getDisplayName();
	Text getListName();
	Location getCompassTarget();
	int getNewExp();
	int getNewLevel();
	int getNewTotalExp();
	boolean shouldKeepLevel();
	double getMaxHealthCache();
	boolean isJoining();
	boolean hasSentListPacket();
	int getClientViewDistance();
	void setDisplayName(String name);
	void setListName(Text listName);
	void setCompassTarget(Location location);
	void setNewExp(int exp);
	void setNewLevel(int level);
	void setNewTotalExp(int exp);
	void setKeepLevel(boolean shouldKeepLevel);
	void setMaxHealthCache(double health);
	void setIsJoining(boolean isJoining);
	void setHasSentListPacket(boolean hasSentListPacket);
	void setClientViewDistance(int distance);
	BlockPos getSpawnPoint(ServerWorld world);
	Entity changeDimension(DimensionType type, PlayerTeleportEvent.TeleportCause cause);
	int nextSyncId();
	void sendMessage(Text[] texts);
	void teleport(ServerWorld worldserver, double x, double y, double z, float pitch, float yaw, org.bukkit.event.player.PlayerTeleportEvent.TeleportCause cause);
	long getTimeOffset();
	boolean isTimeRelative();
	void setTimeOffset(long offset);
	void setRelativeTime(boolean time);
	long getPlayerTime();
	WeatherType getPlayerWeather();
	void setPlayerWeather(WeatherType type);
	void setPlayerWeather(WeatherType type, boolean plugin);
	void updateWeather(float rainGradFrom, float rainGradTo, float thunderGradFrom, float thunderGradTo);
	void tickWeather();
	void resetPlayerWeather();
	void forceSetPositionRotation(double x, double y, double z, float yaw, float pitch);
	void reset();
	// TODO full impl
}
